### ISSUE TITLE
Update Network Policies to allow access to required services.

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-operator#423] opened 2023-08-08 15:19 UTC
The DSCInitialization controller creates network policy that [allows all ](https://github.com/opendatahub-io/opendatahub-operator/blob/main/controllers/dscinitialization/utils.go#L180)traffic in ODH namespaces .

Update the Networkpolicy to allow all traffic only between ODH namespaces(with label opendatahub.io/generated-namespace='true') 

```
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              opendatahub.io/generated-namespace: 'true'
  policyTypes:
    - Ingress
```

Acceptance Criteria

- Creates updated Networkpolicy that allows all traffic between ODH namespaces
- Verify all components work as expected

**Comment by zdtsw** [comment] 2023-08-23 12:28
I assume the change should be similar to RBAC, gathering all networkpolicy and adding them in the operator.

Or should it be just using NWP from manifests ( once the [distribute odh-manifests](https://github.com/opendatahub-io/opendatahub-operator/issues/424) is done for each component) out of the box?

**Comment by zdtsw** [comment] 2023-08-23 13:28
the ones that not in the manifests are
https://github.com/red-hat-data-services/odh-deployer/blob/main/network/monitoring_network_policy.yaml
https://github.com/red-hat-data-services/odh-deployer/blob/main/network/applications_network_policy.yaml
https://github.com/red-hat-data-services/odh-deployer/blob/main/network/operator_network_policy.yaml

**Comment by VaishnaviHire** [comment] 2023-09-07 04:32
> the ones that not in the manifests are https://github.com/red-hat-data-services/odh-deployer/blob/main/network/monitoring_network_policy.yaml https://github.com/red-hat-data-services/odh-deployer/blob/main/network/applications_network_policy.yaml https://github.com/red-hat-data-services/odh-deployer/blob/main/network/operator_network_policy.yaml

I think we should update existing networkpolicy to all all traffic only between ODH namespaces

**Comment by zdtsw** [comment] 2023-09-12 10:41
i think the main problem with this networkpolicy is:
traffic from external (e.g user click Route) cannot access odh-dashboard-*** pod

the requirement should be:
- Allow any pod  to access each other as long as the pod is in the namespace with label "opendatahub.io/generated-namespace: 'true'"
- Restrict access to pods in namespace with label "opendatahub.io/generated-namespace: 'true' from any other namespace.
- Allow access to the dashboard pod in namespace with label "opendatahub.io/generated-namespace: 'true'" via the Route link.

**Comment by zdtsw** [comment] 2023-09-12 14:16
after checking up, the external traffic does not matter to networkpolicy, but for openshift it does need one more namespace which is openshift-ingress to be added

**Comment by zdtsw** [comment] 2023-09-20 08:19
i will have to revert this first to unblock ODH nightly test.
the change is not working on a PSI cluster, and i will need to test it on PSI before next PR.....

**Comment by zdtsw** [comment] 2023-09-21 13:44
tested it on the nightly cluster but cannot see problem.
will keep this issue open and have "main" with "open policy" for another nightly test by QE

**Comment by zdtsw** [comment] 2023-09-22 15:32
still cannot reproduce the same error in QE's cluster.

will need to work with QE next week and see if it is something the way how they installed operator is not correct

**Comment by zdtsw** [comment] 2023-10-03 15:58
i removed the 1.34 label, dont think we will get the change ready to sync downstream by this friday. unless odh nightly gets to work tomorrow

**Comment by zdtsw** [comment] 2023-11-25 16:08
close this issue as in odh-2.4 we have created networkpolicy to only allow odh generated and certain openshift namespaces to be communicated among with.

**Closed by zdtsw** 2023-11-25 16:08 UTC
Labels: priority/high

**Comment by Jooho** [comment] 2023-12-07 20:29
@zdtsw @VaishnaviHire With this PR, we can expect that odh-operator will create a networkpolicy into user namespaces that were created by UI, right?  The networkpolicy in the user namespace will allow requests from `redhat-ods-applications`. am I right?

**Comment by zdtsw** [comment] 2023-12-08 06:09
i dont follow this question:  what you mean user namespaces? 
can you give an example

**Comment by Jooho** [comment] 2023-12-08 13:53
user namespace is what the user created. Not the namespace that has openshift AI components(kserve/modelmesh/DS and so on)

example)

redhat-ods-application(rhoai NS)                                                  kserve-demo (user NS)
                              ------------------------------------------------------------------------>    B
               A            <------------------------------------------------------------------------      

A networkpolicy can allow ingress requests from user NS, B networkpolicy can allow ingress requests from rhoai NS.

My question is odh-operator will create the B networkpolicy or not with this PR.

**Comment by zdtsw** [comment] 2023-12-08 14:04
no B in your example is created by this PR

you can read code here https://github.com/opendatahub-io/opendatahub-operator/blob/main/controllers/dscinitialization/utils.go#L243
