### ISSUE TITLE
"No Components Found" page randomly appears instead of Enabled page in RHODS dashboard

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/opendatahub-operator#498] opened 2023-08-31 09:24 UTC
**Describe the bug**
This is an issue I have not been able to reproduce manually to investigate further, but roughly once every automated test run we see some test failing because of the page seen in the screenshot. It appears that for some reason the `Jupyter` tile is not found/loaded and this placeholder page is shown instead

**To Reproduce**
Not sure

**Expected behavior**
This page should never appear ideally

**Screenshots**
![image](https://github.com/opendatahub-io/opendatahub-operator/assets/82518733/7cc87889-03f8-4d33-a1c2-9175449bc855)

**Additional context**

**Comment by zdtsw** [comment] 2023-09-15 13:59
i doubt could that be  [ const retComponents = useDeepCompareMemoize<OdhApplication[]>(components);](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/utilities/useWatchComponents.tsx#L44)
cause the "no components found" message?

**Comment by zdtsw** [comment] 2023-09-15 14:02
if this happens every time in the automation and causing smoke test failure, worth asking UI team take a look
but we can wait for another week, till https://github.com/opendatahub-io/opendatahub-operator/issues/531 is closed and see if still reproducible.  @lugi0

**Comment by lugi0** [comment] 2023-09-25 07:54
@zdtsw do you know what's the ETA for #531? This keeps happening in our automated test runs - if it can help pinpoint the issue it appears to always be the first time the dashboard is loaded after installation

**Comment by lugi0** [comment] 2023-09-25 08:02
(cc @andrewballantyne @lucferbux if you folks have any idea)

**Comment by zdtsw** [comment] 2023-09-25 08:15
> @zdtsw do you know what's the ETA for #531? This keeps happening in our automated test runs - if it can help pinpoint the issue it appears to always be the first time the dashboard is loaded after installation

we are aiming to get #531 out in ODH 1.10 which should happen either today or tomorrow.
but i think it is good if UI team leads can triage it as well.

**Comment by andrewballantyne** [comment] 2023-09-25 15:36
@lugi0 either we need to view your automation and investigate the cluster at time of failure, or you need to provide steps for us to reproduce this in isolation. I'm unsure what we can do other than run around poking at it. I have seen this work plenty of times, so I'm at a loss what we can do to solve this as I do not know how it happens.

@zdtsw have you guys setup the bot yet, can we transfer this to the Dashboard repo? It is unlikely moving the component source over to the Dashboard will fix this as I think you had a reasonably updated copy of them.

**Comment by lugi0** [comment] 2023-09-26 08:00
>or you need to provide steps for us to reproduce this in isolation

@andrewballantyne as far as I was able to see, this seems to happen only once, the first time the dashboard is accessed after a RHODS install *on a fresh cluster*. Repeat installs of RHODS on the same cluster do not seem to trigger it.
I'm still trying to pin down a reproducer for this, but other than this observations from the automated runs I have not been able to trigger it manually.

**Comment by lugi0** [comment] 2023-09-26 12:24
@andrewballantyne just retested this on a fresh cluster; after installing RHODS for the first time, the error appeared the third time the dashboard was visited.
I've then rerun all of the tests (twice) and it did not appear again.
My best guess is that this is a one off on new clusters, happening in the first few times the dashboard is visited.
Sorry I can't give you a more precise answer :(

**Comment by andrewballantyne** [comment] 2023-09-26 18:49
Well that's frustrating lol -- I can't even begin to guess where the problem would be. It's a web of questionable logic we have in there since it dates back to the early days of the Dashboard. We'll need to know more before we can investigate.

**Comment by lucferbux** [comment] 2023-09-27 07:30
@lugi0 @andrewballantyne we are slightly tweaking the logic of retrieval in the Jupyterhub deprecation, since this is not a clear bug, why don't we wait for those changes and revisit this, in case that's fixed.
If we manage to replicate this in a controlled environment, we can try to properly fix it but I would say this might be happening for several reasons.

**Comment by lugi0** [comment] 2023-10-09 08:52
@lucferbux not sure if the tweaking of the logic is included in the 1.34 RC build, but this has happened again today on the automated run

**Comment by lucferbux** [comment] 2023-10-09 12:03
@lugi0 no, this is still in a feature branch, we need to test if it's working properly to include it in a new release.

**Comment by AjayJagan** [comment] 2023-12-06 18:37
Moved this issue to JIRA ref: https://issues.redhat.com/browse/RHOAIENG-404

**Comment by zdtsw** [comment] 2023-12-07 08:21
do we still need this issue?  @lucferbux @lugi0

**Comment by AjayJagan** [comment] 2023-12-12 07:26
I have created a JIRA for the same so we can have a ref for this(In case we need to re-open). Hence closing it here.

**Closed by AjayJagan** 2023-12-12 07:26 UTC
Labels: bug
